name: qe-lectures
channels:
  - default
  - conda-forge
dependencies:
  - pip
  - python
  - jupyter
  - jupyterlab
  - nbconvert
  - pandoc
  - pandas
  - numba=0.46
  - numpy
  - matplotlib
  - networkx
  - sphinx=2.4.4
  - scikit-learn
  - statsmodels
  - seaborn
  - pip:
    - sphinxcontrib-jupyter
    - sphinxcontrib-bibtex
    - quantecon
    - joblib
