name: qe-lectures
channels:
  - default
  - conda-forge
dependencies:
  - pip
  - python
  - jupyter
  - jupyterlab
  - nbconvert=5.6.1
  - pandoc
  - pandas
  - numba
  - numpy
  - matplotlib
  - networkx
  - sphinx=2.4.4
  - scikit-learn
  - statsmodels
  - seaborn
  - scipy
  - sympy
  - pip:
    - interpolation
    - sphinxcontrib-jupyter
    - sphinxcontrib-bibtex
    - joblib