name: qe-lectures
channels:
  - default
  - conda-forge
dependencies:
  - pip
  - python
  - jupyter
  - jupyterlab
  - nbconvert
  - pandoc
  - pandas
  - numba
  - numpy
  - matplotlib
  - networkx
  - sphinx=2.4.4
  - pip:
    - sphinxcontrib-jupyter 
    - sphinxcontrib-bibtex 
    - quantecon 
    - joblib
